#!/usr/bin/env php
<?php
use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Debug\Debug;

set_time_limit(0);
require 'vendor/autoload.php';
Debug::enable();
$kernel = new AppKernel('dev', true);
$application = new Application($kernel);
$application->run();
